### ISSUE TITLE
Improve site design

### ISSUE THREAD

**Issue by sinayra** [sinayra/jojo-cover#5]
I feel the layout is not that great, but I'm having a hard time to discover what I should change by myself.

**Comment by GustavoTxFreitas-zz** [comment]
### Howdy, @sinayra! (=^ • u • ^=)

I've been designing some solutions to improve the layout of the application, so I would like to test it on the fork I made from the repository. However, I had problems rotating the page on my local machine, yare yare, here is the error:

```node
ERROR #98123  WEBPACK
Generating development JavaScript bundle failed
Module build failed (from ./node_modules/gatsby/node_modules/css-loader/index.js): 

TypeError: aSourceMapConsumer.originalPositionFor is not a function at SourceMapGenerator.
<anonymous> (./node_modules/gatsby/node_modules/source-map/lib/source-map-generator.js:204:45)
at Array.forEach(<anonymous>)
at MappingList.unsortedForEach ./node_modules/gatsby/node_modules/source-map/lib/mapping-list.js:44:17)
at SourceMapGenerator.applySourceMap (./node_modules/gatsby/node_modules/source-map/lib/source-map-generator.js:201:20)
at MapGenerator.applyPrevMaps (./node_modules/gatsby/node_modules/postcss/lib/map-generator.es6:107:22) 
at MapGenerator.generateMap (./node_modules/gatsby/node_modules/postcss/lib/map-generator.es6:169:48)
at MapGenerator.generate (./node_modules/gatsby/node_modules/postcss/lib/map-generator.es6:269:25)
at LazyResult.stringify (./node_modules/gatsby/node_modules/postcss/lib/lazy-result.es6:351:24)
at ./node_modules/gatsby/node_modules/postcss/lib/lazy-result.es6:299:25 

File: src/components/footer.module.css failed
Building development bundle - 41.866s
```
> "oh nooooo"

You may have some instructions on how to resolve this issue, otherwise, contact me with other alternatives to run this repo.
I would be very grateful to be able to contribute to the growth of your project.

Available for anything,
[Gustavo Teixeira](https://github.com/GustavoTxFreitas).

**Comment by sinayra** [comment]
Hi @GustavoTxFreitas !! Thank you for helping me!

I must confess that I never faced this kind of error before.... However, looking back to this project and running it locally, I found out that it was missing a dependency on package.json. I added now and, after installing all dependencies, I think it should run with `npm run develop`. Do have more information about your environment?

**Comment by GustavoTxFreitas-zz** [comment]
After some modifications to `package-lock.json`, I was successful in running the application.
Thank you very much for your tips!

NPM did not allow the installation of some dependencies that your project is using,
as most of them have been **discontinued**. It may be a good idea to check this to avoid security breaches in the future.

I'll start the layout changes tomorrow, soon I'll bring you news.

**Comment by sinayra** [comment]
Awesome! I just used a Gatsby template for typescript and to start this project and didn't think much about security and stuff, hahaha
Thank you very much for noticing that! I'll take a look as soon as possible.
